[server]
bind_address = "0.0.0.0"
port = 58081
cors_origins = ["*"]
request_timeout = 30

[models]
directory = "./HuggingFace"
max_loaded_models = 2
default_quantization = "int8"
context_window = 4096

[limits]
max_request_size = 1048576  # 1MB
max_concurrent_requests = 100
rate_limit_per_minute = 60

[logging]
level = "info"
format = "json"